title: "Free Spins No Deposit 2026"
description: "Best free spins no deposit casino bonuses. 122 verified offers, exclusive promo codes, USA accepted."
url: "https://bestnodepositspins.github.io"
baseurl: "/free-spins"

markdown: kramdown
plugins:
  - jekyll-datapage_gen
  - jekyll-sitemap
  - jekyll-seo-tag

page_gen:
  - data: casinos
    template: casino
    name: slug
    dir: free-spins-no-deposit
    filter_condition: "record['page_type'] == 'casino'"
  - data: casinos
    template: general
    name: slug
    dir: free-spins-no-deposit
    filter_condition: "record['page_type'] == 'general'"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
